### ISSUE TITLE
Flipped/rotated tiles are not displayed properly

### ISSUE THREAD

**Issue by tiefpunkt** [MichaelKreil/rc3-map-scraper#1]
Tiles can be rotated and flipped. If that has happened on the map, those tiles are not displayed.

Tile flipping is done with the three highest bits in the data array of a layer, as described here: https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping

Not much of a JS guru myself, but I'll try to figure this out.

**Comment by tiefpunkt** [comment]
I can read the flags, and all tiles are shown now, but no rotation/flipping is applied yet.

**Comment by MichaelKreil** [comment]
Thank you for pointing that out, and also for fixing it!
